apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 3
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 2
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: app-deployment
          image: siddharthbhardwaj99/todo-flask:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_HOST 
              value: "mongodb-service.default.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: FLASK_ENV 
              value: development
            - name: PORT
              value: "8000"