apiVersion: v1
kind: ReplicationController
metadata:
  name: app-replication
spec:
  replicas: 5
  selector:
    app: app-deployment
  template:
    metadata:
      name: app-deployment
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-deployment
        image: siddharthbhardwaj99/todo-flask:latest
        ports:
        - containerPort: 8000
