version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=camp2016
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - backend

  flask:
    build: ./app
    container_name: flask
    image: flask:latest
    restart: unless-stopped
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      FLASK_ENV: development
      PORT: 8000
    volumes:
      - app:/data
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb:
    driver: local
  app:
    driver: local
